# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'T_USER',
                'ordering': ['create_date'],
            },
        ),
    ]
